/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:d06def0b-96f9-4620-bc3a-613ee49ed30f",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_RZ0Vx5twn",
    "aws_user_pools_web_client_id": "7inaf3b3tm45huceu0j5hjaa3o",
    "oauth": {},
    "aws_user_files_s3_bucket": "photodemobeta241dbb56c5f7b4bf89ec609f548f61190183539-dev",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
